// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCxr46Sl3jfrv78AsRZgm6ATHRcoghuEIo',
    appId: '1:771713067940:web:cc57c62cfdff8cf83e2f31',
    messagingSenderId: '771713067940',
    projectId: 'green-bin-customer-92130',
    authDomain: 'green-bin-customer-92130.firebaseapp.com',
    storageBucket: 'green-bin-customer-92130.firebasestorage.app',
    measurementId: 'G-KX3EN0Y9C7',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAb4dzI-XwgZFfVaA7cmed9pu3pj8a5HZc',
    appId: '1:771713067940:android:9f298ca37ea38e953e2f31',
    messagingSenderId: '771713067940',
    projectId: 'green-bin-customer-92130',
    storageBucket: 'green-bin-customer-92130.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBlNoY3aY6lATr_aI5_-ykBSXLATqGg3eQ',
    appId: '1:771713067940:ios:cc00948349cd11d43e2f31',
    messagingSenderId: '771713067940',
    projectId: 'green-bin-customer-92130',
    storageBucket: 'green-bin-customer-92130.firebasestorage.app',
    iosBundleId: 'com.example.greenBinEmployee',
  );
}
